version: '3.7'
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    tty: true
    entrypoint:
      - yarn
      - start
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
  db:
    container_name: db
    image: postgres:11.6-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
