 
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 'db'
  port: 5432
  username: 'postgres'
  password: nil

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test

production:
  <<: *default
  database: prod