name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Commit or branch to Deploy'
        required: true
        default: 'master'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref }}
    - run: |
        echo "Hello ${{ github.event.inputs.ref }}!"
        cat hola.txt
